services:
  peer1:
    build: .
    container_name: bully-peer1
    command: --id 1
    env_file: backend/peers.env
    ports:
      - "9000:9000/udp"
    volumes:
      - ./backend/peers.env:/app/peers.env:ro
      - ./backend/state:/app/state
    depends_on:
      - peer2

  peer2:
    build: .
    container_name: bully-peer2
    command: --id 2
    env_file: backend/peers.env
    ports:
      - "9001:9000/udp"
    volumes:
      - ./backend/peers.env:/app/peers.env:ro
      - ./backend/state:/app/state

networks:
  default:
    driver: bridge
